### ISSUE TITLE
Unclear in 'file_name' in grefs(unc).json file?

### ISSUE THREAD

**Issue by nero1342** [henghuiding/gRefCOCO#1]
Some items are formatted as {file_name}.jpg, others are in {file_name}_{number}.jpg 

For example:
1. 'ref_id' =  200000 -> 'file_name': 'COCO_train2014_000000388882.jpg'
2. 'ref_id' = 0 -> 'file_name': 'COCO_train2014_000000581857_16.jpg'  

Can you explain this? Or should we just skip the last number in the 'file_name' if it appears?

Thanks.

**Comment by ntuLC** [comment]
Hi for this part we follow the file names used in RefCOCO (https://bvisionweb1.cs.unc.edu/licheng/referit/data/refcoco.zip). You can find the images using image IDs.

Best,
Liu Chang
________________________________
From: Nguyen E Ro ***@***.***>
Sent: Thursday, August 17, 2023 5:02:03 PM
To: henghuiding/gRefCOCO ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [henghuiding/gRefCOCO] Unclear in 'file_name' in grefs(unc).json file? (Issue #1)


Some items are formatted as {file_name}.jpg, others are in {file_name}_{number}.jpg

For example:

  1.  'ref_id' = 200000 -> 'file_name': 'COCO_train2014_000000388882.jpg'
  2.  'ref_id' = 0 -> 'file_name': 'COCO_train2014_000000581857_16.jpg'

Can you explain this? Or should we just skip the last number in the 'file_name' if it appears?

Thanks.
