### ISSUE TITLE
Dataset downoad links are not working.

### ISSUE THREAD

**Issue by TokuhiroNishikawa** [henghuiding/gRefCOCO#2]
Hi, 

I noticed that the download links for the dataset are not working. It would be greatly appreciated if you could take a moment to fix it. Thanks in advance!

**Comment by TokuhiroNishikawa** [comment]
Typo in the issue title. My apologies!

**Comment by ntuLC** [comment]
Hi,

Thanks for raising the issue! The links have been fixed.
