### ISSUE TITLE
关于标注的一些疑问

### ISSUE THREAD

**Issue by hhaAndroid** [henghuiding/gRefCOCO#3]
作者好，非常感谢你提供的新标注。我可视化分析了下你提供的数据，我有两个疑问：

1. 为何有些图片文件名带有 _x 的后缀？ 我看你在之前 issue 里面回复是说参考 RefCOCO的，但是我可视化了 RefCOCO 数据集没有发现他有 _x 的后缀？你能给出一个例子吗？

2. 为何有些 bbox 没有文本？很奇怪。有些文本没有 bbox 这个是合理的，但是为啥有些图片有 bbox  没有文本？这是啥任务？

来自图片 COCO_train2014_000000002567.jpg 标注可视化：
![image](https://github.com/henghuiding/gRefCOCO/assets/17425982/ee553de7-f464-49aa-b374-9cc0c091dc1f)

你看最右边的那个图，有 bbox 但是没有文本，你能解释下为啥吗

**Comment by ntuLC** [comment]
你好，
1. 请以image_id为准。refcoco也有的：
![r](https://github.com/henghuiding/gRefCOCO/assets/54399045/a50a86d2-6d77-4516-968b-6d132abd224a)

2. 加载数据集时以sentence为单位读取，跳过空ref即可，没有影响。请参考dataloader: 
https://github.com/henghuiding/ReLA/blob/1cf1e9fe46cd69fea44e1cbe7917e599e895e438/gres_model/data/datasets/grefcoco.py#L131
https://github.com/henghuiding/gRefCOCO/blob/main/mdetr/scripts/fine-tuning/grefexp_coco_format.py#L79

**Comment by hhaAndroid** [comment]
@ntuLC 非常感谢！同时也非常感谢数据集开源
