### ISSUE TITLE
F1_score 就是论文里面的 Pr@(F1=1, IoU≥0.5)吗？

### ISSUE THREAD

**Issue by hhaAndroid** [henghuiding/gRefCOCO#4]
作者好，看计算过程，应该 F1_score 就是论文里面的 Pr@(F1=1, IoU≥0.5)？想确认下？我们正在使用你的数据集和评测指标

**Comment by hhaAndroid** [comment]
我直接用 groundingdino-t 权重进行评测(zero-shot)，结果如下：

| Method                                  | Grounding DINO-T  |
|-----------------------------------------|-------------------|
| gRefCOCO val Pr@(F1=1, IoU≥0.5),N-acc   | 41.32/91.82       |
| gRefCOCO testA Pr@(F1=1, IoU≥0.5),N-acc | 27.23/90.24       |
| gRefCOCO testB Pr@(F1=1, IoU≥0.5),N-acc | 29.70/93.49       |

结果是否合理？麻烦作者确认下

**Comment by heshuting555** [comment]
> 作者好，看计算过程，应该 F1_score 就是论文里面的 Pr@(F1=1, IoU≥0.5)？想确认下？我们正在使用你的数据集和评测指标

Thank you for your interest!

Yes!

**Comment by heshuting555** [comment]
> 我直接用 groundingdino-t 权重进行评测(zero-shot)，结果如下：
> 
> Method	Grounding DINO-T	Grounding DINO-B
> gRefCOCO val Pr@(F1=1, IoU≥0.5),N-acc	41.32/91.82	46.18/81.44
> gRefCOCO testA Pr@(F1=1, IoU≥0.5),N-acc	27.23/90.24	38.60/76.06
> gRefCOCO testB Pr@(F1=1, IoU≥0.5),N-acc	29.70/93.49	35.87/80.58
> 结果是否合理？麻烦作者确认下

F1_score 看起来挺合理的。但N_acc 有点高，你的输出策略是什么？似乎是倾向输出较少的bbox？

**Comment by hhaAndroid** [comment]
N_acc 高是因为他的输出策略是大于0.7的框少，如果你都没有 target，那几乎就不会预测出 bbox，因此高是合理的

**Comment by heshuting555** [comment]
你的分析是对的，当输出策略倾向于输出较少的bbox时，N_acc就会高，但这是以牺牲F1_score为代价的。极端情况下如果选择不输出任何bbox，N_acc会达到1，F1_score则会降为0。如果想要N_acc和F1_score都高，则需要模型预测出更多准确且高分的bbox。

**Comment by hhaAndroid** [comment]
感谢，那我的评测应该没有问题了

**Comment by Dmmm1997** [comment]
> 你的分析是对的，当输出策略倾向于输出较少的bbox时，N_acc就会高，但这是以牺牲F1_score为代价的。极端情况下如果选择不输出任何bbox，N_acc会达到1，F1_score则会降为0。如果想要N_acc和F1_score都高，则需要模型预测出更多准确且高分的bbox。

我觉得这个评估过程存在问题，当没有预测框时，F1_score仍然会有得分，因为测试集中存在大量的没有gt的样本，这些样本在 没有预测的时候会提高F1_score。据个人统计，val集合 在不预测任何结果的时候的F1_score为0.4左右，而N_acc可以达到1.0。另外，通过预测对所有样本来提高F1_score对模型的要求非常高，我个人对该评价方式感到质疑。
