### ISSUE TITLE
The number of expressions on gRefCOCO

### ISSUE THREAD

**Issue by SouthFlame** [henghuiding/gRefCOCO#6]
Dear author,

Thanks for the valuable and interesting work :).
To be clear, I kindly ask why the number of expressions of "gref(unc).json" is "259,859", not "278,232" as your paper states.
Even though I know that it is not crucial for your amazing work, I just ask for the details in order to refer your dataset precisely.

Kind regards

**Comment by changliu19** [comment]
Hi, thank you for your interest!  A small potion of data (~6%) is temporarily held for future challenge use. We will update you when the challenge is on live. By the way, we also kindly invite you to take a look at our ongoing challenges: [MOSE](https://henghuiding.github.io/MOSE/ChallengeCVPR2024) and [MeVis](https://henghuiding.github.io/MeViS/ChallengeCVPR2024). Thanks!

**Comment by SouthFlame** [comment]
Alright! Thanks for the detail. :). Of course, I will pay attention to the great workshop (I already knew it, to be honest ;)), and I hope the workshop is going well!
